// Centralised icon registry. One import path for the whole app so we can
// swap the icon library without touching every feature file.
//
// Design rule: icons are monochrome outlines (Lucide default stroke 2).
// Feature icons render at 24-32px, UI chrome at 16-20px. Use the theme's
// accent colour via the `className="..."` prop, not a hardcoded fill.
import {
  Home,
  BookOpen,
  Tv,
  ListChecks,
  HelpCircle,
  Puzzle as PuzzleIcon,
  Pencil,
  History,
  Clock,
  Heart,
  CalendarHeart,
  Plane,
  Cake,
  Pin,
  Settings,
  X,
  Plus,
  Check,
  Copy,
  Trash2,
  LogOut,
  Link2,
  Flame,
  ListMusic,
  Play,
  SkipForward,
  Brush,
  AlertTriangle,
  MessageCircle,
  BookMarked,
  CheckCircle2,
  PenLine,
  UserRound,
  Menu,
  Share2,
  Sprout,
  Sparkles,
  Zap,
  Gift,
  Lock,
  Smartphone,
  ArrowLeft,
  ArrowUp,
  Target,
  Map,
  Info,
  Music,
  Music2,
  Pause,
  RotateCw,
  Bookmark,
  Inbox,
  Send,
  Eraser,
  Smile,
  HandHeart,
  Mail,
  Camera,
  Download,
  Film,
  ChevronRight,
} from 'lucide-react'

// Small helper — passes through className, defaults size/strokeWidth.
// Letting callers control size via Tailwind (e.g. `h-5 w-5`) is cleaner
// than juggling a `size` prop alongside `className`.
export {
  Home,
  BookOpen,
  Tv,
  ListChecks,
  HelpCircle,
  PuzzleIcon,
  Pencil,
  History,
  Clock,
  Heart,
  CalendarHeart,
  Plane,
  Cake,
  Pin,
  Settings,
  X,
  Plus,
  Check,
  Copy,
  Trash2,
  LogOut,
  Link2,
  Flame,
  ListMusic,
  Play,
  SkipForward,
  Brush,
  AlertTriangle,
  MessageCircle,
  BookMarked,
  CheckCircle2,
  PenLine,
  UserRound,
  Menu,
  Share2,
  Sprout,
  Sparkles,
  Zap,
  Gift,
  Lock,
  Smartphone,
  ArrowLeft,
  ArrowUp,
  Target,
  Map,
  Info,
  Music,
  Music2,
  Pause,
  RotateCw,
  Bookmark,
  Inbox,
  Send,
  Eraser,
  Smile,
  HandHeart,
  Mail,
  Camera,
  Download,
  Film,
  ChevronRight,
}

// Feature → nav icon. Single source of truth for nav + dashboard grid.
export const FEATURE_ICONS = {
  dashboard: Home,
  journal:   BookOpen,
  watch:     Tv,
  bucket:    ListChecks,
  trivia:    HelpCircle,
  puzzle:    PuzzleIcon,
  draw:      Pencil,
  music:     Music2,
  timeline:  History,
}

// Milestone kind → icon. Keeps the visual personality of the old
// emojis (✈️ 💝 🎂 📌) but consistent across devices.
export const MILESTONE_ICONS = {
  visit:       Plane,
  anniversary: CalendarHeart,
  birthday:    Cake,
  custom:      Pin,
}
