const PROMPTS = [
  "What's one thing about today you wish you could share with me in person?",
  "Describe your perfect lazy day together.",
  "What song has been stuck in your head lately?",
  "What's something small that made you smile today?",
  "If we could teleport anywhere right now, where would you take us?",
  "What's a movie or show you want us to watch together next?",
  "What's one thing you learned recently that surprised you?",
  "Describe a memory of us that you keep coming back to.",
  "What are you most looking forward to this week?",
  "What's something you've been wanting to tell me but haven't found the right moment?",
  "If today were a colour, what would it be and why?",
  "What's a dream you had recently — sleeping or waking?",
  "What do you miss most about me right now?",
  "What's something you've been proud of yourself for lately?",
  "What's one thing you wish I knew about your day without having to explain it?",
  "What food are you craving right now, and would you make it for me someday?",
  "What's a place in your city I haven't seen that you want to show me?",
  "What's one habit or routine of yours that you think I'd find endearing?",
  "What made you laugh out loud recently?",
  "What's something you're working towards right now?",
  "If we lived together, what would our mornings look like?",
  "What's a word that describes how you're feeling today?",
  "What's one thing you appreciate about yourself right now?",
  "What's a random fact you learned this week?",
  "What does home feel like to you?",
  "What's something you've been overthinking lately?",
  "What's a small act of kindness you gave or received today?",
  "What's one thing you'd want to change about this week?",
  "If you could send me one physical thing right now, what would it be?",
  "What does a good night look like for you lately?",
  "What's a future version of us you think about?",
  "What's something that has been challenging you lately?",
  "What's one thing that always cheers you up?",
  "What are three words that describe today?",
  "What's something new you want to try together?",
  "What's something from your childhood you want to share with me someday?",
  "What does missing me feel like to you right now?",
  "What's one thing you're grateful for today?",
  "What's a goal you're quietly working on?",
  "What's the best part of talking to me?",
  "What would you tell yourself a year ago?",
  "What's a small luxury that makes your day better?",
  "What are you reading, watching, or listening to that's moving you lately?",
  "What's something that scared you but you did it anyway?",
  "If we had one free day together next week, how would you plan it?",
  "What's something you've forgiven yourself for lately?",
  "What's your current favourite spot at home and why?",
  "What does love look like to you in the small moments?",
  "What's one thing you want more of in your life right now?",
  "What would you want our story to look like five years from now?",
]

export function getDailyPrompt() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000)
  return PROMPTS[dayOfYear % PROMPTS.length]
}
