// All class strings must be written in full so Tailwind doesn't purge them.
export const THEMES = {
  rose: {
    name: 'Rose', emoji: '🌹',
    appBg:        'bg-rose-50',
    headerBg:     'bg-white border-rose-100',
    navActive:    'border-rose-500 text-rose-600',
    navHover:     'hover:text-rose-500',
    card:         'border-rose-100',
    btn:          'bg-rose-500 hover:bg-rose-600 text-white',
    btnOutline:   'border-rose-300 text-rose-600 hover:bg-rose-50',
    accent:       'text-rose-500',
    accentBg:     'bg-rose-50',
    accentBorder: 'border-rose-200',
    codeBg:       'bg-rose-50 border-rose-200 hover:bg-rose-100 hover:border-rose-400',
    codeText:     'text-rose-500',
    badge:        'bg-rose-50 text-rose-600',
    ring:         'focus:border-rose-300',
    check:        'accent-rose-500',
    myBubble:     'bg-rose-500 text-white',
    myEntry:      'bg-rose-50',
    indicator:    'text-rose-400',
  },
  violet: {
    name: 'Violet', emoji: '💜',
    appBg:        'bg-violet-50',
    headerBg:     'bg-white border-violet-100',
    navActive:    'border-violet-500 text-violet-600',
    navHover:     'hover:text-violet-500',
    card:         'border-violet-100',
    btn:          'bg-violet-500 hover:bg-violet-600 text-white',
    btnOutline:   'border-violet-300 text-violet-600 hover:bg-violet-50',
    accent:       'text-violet-500',
    accentBg:     'bg-violet-50',
    accentBorder: 'border-violet-200',
    codeBg:       'bg-violet-50 border-violet-200 hover:bg-violet-100 hover:border-violet-400',
    codeText:     'text-violet-500',
    badge:        'bg-violet-50 text-violet-600',
    ring:         'focus:border-violet-300',
    check:        'accent-violet-500',
    myBubble:     'bg-violet-500 text-white',
    myEntry:      'bg-violet-50',
    indicator:    'text-violet-400',
  },
  sky: {
    name: 'Sky', emoji: '💙',
    appBg:        'bg-sky-50',
    headerBg:     'bg-white border-sky-100',
    navActive:    'border-sky-500 text-sky-600',
    navHover:     'hover:text-sky-500',
    card:         'border-sky-100',
    btn:          'bg-sky-500 hover:bg-sky-600 text-white',
    btnOutline:   'border-sky-300 text-sky-600 hover:bg-sky-50',
    accent:       'text-sky-500',
    accentBg:     'bg-sky-50',
    accentBorder: 'border-sky-200',
    codeBg:       'bg-sky-50 border-sky-200 hover:bg-sky-100 hover:border-sky-400',
    codeText:     'text-sky-500',
    badge:        'bg-sky-50 text-sky-600',
    ring:         'focus:border-sky-300',
    check:        'accent-sky-500',
    myBubble:     'bg-sky-500 text-white',
    myEntry:      'bg-sky-50',
    indicator:    'text-sky-400',
  },
  emerald: {
    name: 'Sage', emoji: '🌿',
    appBg:        'bg-emerald-50',
    headerBg:     'bg-white border-emerald-100',
    navActive:    'border-emerald-600 text-emerald-700',
    navHover:     'hover:text-emerald-600',
    card:         'border-emerald-100',
    btn:          'bg-emerald-600 hover:bg-emerald-700 text-white',
    btnOutline:   'border-emerald-300 text-emerald-700 hover:bg-emerald-50',
    accent:       'text-emerald-600',
    accentBg:     'bg-emerald-50',
    accentBorder: 'border-emerald-200',
    codeBg:       'bg-emerald-50 border-emerald-200 hover:bg-emerald-100 hover:border-emerald-400',
    codeText:     'text-emerald-600',
    badge:        'bg-emerald-50 text-emerald-700',
    ring:         'focus:border-emerald-300',
    check:        'accent-emerald-600',
    myBubble:     'bg-emerald-600 text-white',
    myEntry:      'bg-emerald-50',
    indicator:    'text-emerald-500',
  },
  slate: {
    name: 'Mauve', emoji: '🩶',
    appBg:        'bg-slate-100',
    headerBg:     'bg-white border-slate-200',
    navActive:    'border-slate-700 text-slate-800',
    navHover:     'hover:text-slate-700',
    card:         'border-slate-200',
    btn:          'bg-slate-700 hover:bg-slate-800 text-white',
    btnOutline:   'border-slate-400 text-slate-700 hover:bg-slate-50',
    accent:       'text-slate-700',
    accentBg:     'bg-slate-50',
    accentBorder: 'border-slate-300',
    codeBg:       'bg-slate-100 border-slate-300 hover:bg-slate-200 hover:border-slate-500',
    codeText:     'text-slate-700',
    badge:        'bg-slate-100 text-slate-700',
    ring:         'focus:border-slate-400',
    check:        'accent-slate-700',
    myBubble:     'bg-slate-700 text-white',
    myEntry:      'bg-slate-100',
    indicator:    'text-slate-500',
  },
}

export const DEFAULT_THEME = 'rose'
